export const DomainErrorCode = {
  // Identity / Value Object errors
  INVALID_EMAIL: 'INVALID_EMAIL',
  DISPOSABLE_EMAIL_DOMAIN: 'DISPOSABLE_EMAIL_DOMAIN',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  COMMON_PASSWORD: 'COMMON_PASSWORD',
  INVALID_TENANT_ID: 'INVALID_TENANT_ID',
  INVALID_USER_ID: 'INVALID_USER_ID',
  INVALID_IDENTITY_ID: 'INVALID_IDENTITY_ID',
  INVALID_SESSION_ID: 'INVALID_SESSION_ID',
  INVALID_TOKEN_ID: 'INVALID_TOKEN_ID',

  // User aggregate errors
  CANNOT_ACTIVATE_WITHOUT_VERIFIED_IDENTITY: 'CANNOT_ACTIVATE_WITHOUT_VERIFIED_IDENTITY',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  MAX_IDENTITIES_PER_TYPE_EXCEEDED: 'MAX_IDENTITIES_PER_TYPE_EXCEEDED',
  IDENTITY_ALREADY_LINKED: 'IDENTITY_ALREADY_LINKED',
  IDENTITY_NOT_FOUND: 'IDENTITY_NOT_FOUND',

  // Identity entity errors
  IDENTITY_ALREADY_VERIFIED: 'IDENTITY_ALREADY_VERIFIED',

  // Session aggregate errors
  INVALID_SESSION_TRANSITION: 'INVALID_SESSION_TRANSITION',
  SESSION_ALREADY_TERMINATED: 'SESSION_ALREADY_TERMINATED',

  // Auth policy errors
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',

  // ABAC condition errors
  INVALID_ABAC_CONDITION: 'INVALID_ABAC_CONDITION',

  // OTP errors
  INVALID_OTP: 'INVALID_OTP',
  OTP_ALREADY_USED: 'OTP_ALREADY_USED',
  OTP_EXPIRED: 'OTP_EXPIRED',

  // Token errors
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',

  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  IDENTITY_ALREADY_EXISTS: 'IDENTITY_ALREADY_EXISTS',

  // OAuth errors
  INVALID_OAUTH_STATE: 'INVALID_OAUTH_STATE',

  // Query / authorization errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
